### ISSUE TITLE
🐛 Delete Volume Request Returning a Virtual Machine

### ISSUE THREAD

**Issue by danquack** [drewmullen/harvester-go-sdk#4]
The delete api is marshaling to the wrong type, causing an error to be thrown. Requests made to DeleteNamespacedPersistentVolumeClaimExecute, should return `K8sIoV1PersistentVolumeClaim` not `KubevirtIoApiCoreV1VirtualMachine`.

References:
https://github.com/drewmullen/harvester-go-sdk/blob/v1.3.0/api_volumes.go#L208-L209
https://github.com/drewmullen/harvester-go-sdk/blob/v1.3.0/api/openapi.json#L410-L425

Example:
```
DELETE /k8s/clusters/c-m-no/api/v1/namespaces/default/persistentvolumeclaims/gotests-5zv5x HTTP/2
Host: rancher.example.com
Content-Type: application/json
Accept: application/json
User-Agent: OpenAPI-Generator/1.0.0/go
Authorization: Bearer redacted
Content-Length: 3
Accept-Encoding: gzip, deflate, br

{}
```

```
HTTP/2 200 OK

{"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata": ...
```

**Comment by drewmullen** [comment]
upstream harvester/harvester is also wrong but not `VirtualMachine`: https://github.com/harvester/harvester/blob/v1.3/api/openapi-spec/swagger.json#L410-L425

**Comment by drewmullen** [comment]
issue was introduced at commit: https://github.com/drewmullen/harvester-go-sdk/commit/6a798d55152bad013bbad2a2c0d8e5a178d04512

**Comment by drewmullen** [comment]
fixed by: https://github.com/drewmullen/harvester-go-sdk/commit/98c06380626c35b238734af9230252a7e7f8cd9e
